export { default as DetallePersonajes } from './DetallePersonajes'
export { default as Inicio } from './Inicio'
export { default as NoFound } from './NoFound'
export { default as PaginaInicial } from './PaginaInicial'
export {default as Episodios} from './Episodios'